# Top-level Makefile
# Builds everything: planet, Python interface and CLI interface

CC     = /usr/lib/ggdb
# -MMD -MP make the compiler emit a .d file per object listing every header that object included.
# Those are pulled in at the bottom, which is what makes editing a header rebuild the objects that
# actually use it. WITHOUT THIS THE BUILD IS NOT MERELY STALE, IT IS UNSAFE: adding a data member
# to cUranusModel recompiled only the two .cpp files that had themselves changed, leaving ten
# objects built against the old class layout, and the resulting binary died in
# `munmap_chunk(): invalid pointer` during resetArrays. A silently wrong object file is worse than
# a failed build. -MP adds a phony target per header so a renamed or deleted header does not
# wedge the build with "No rule to make target".
CFLAGS = -Wall -fPIC -std=c++11 -Ilib -Iplanet -Itinyxml2 -fopenmp -MMD -MP


# Common files for the shared lib (libaturan.a)
LIB_OBJ = lib/Array.o lib/Array_2D.o lib/Array_1D.o lib/Config.o lib/Utils.o lib/FFT.o

ATURAN_OBJ = planet/cUranusModel.o planet/PrintMsg_Uran.o planet/RungeKutta_Uran.o \
planet/RHS_Uran.o planet/ParaView_Uran.o planet/Thermo_Uran.o \
planet/InitVariables_Uran.o planet/InitVelocity_Uran.o planet/FileIO_Uran.o \
planet/Pressure_Uran.o planet/SaturationAdjustmentUran.o \
planet/Delegations_Uran.o planet/BC_Uran.o

XML_OBJ = tinyxml2/tinyxml2.o

# Command line objects
ATURAN_CLI_OBJ = cli/uran.o cli/DefaultStream.o

# The per-object header lists written by -MMD, pulled in at the bottom of this file.
DEPS = $(LIB_OBJ:.o=.d) $(ATURAN_OBJ:.o=.d) $(XML_OBJ:.o=.d) $(ATURAN_CLI_OBJ:.o=.d)

# Because there are so many parameters, many of the files are autogenerated
PARAM_OUTPUTS = planet/cUranusDefaults.cpp.inc planet/UranusLoadConfig.cpp.inc \
planet/UranusParams.h.inc uranus/config_aturan.xml python/uranus_pxd.pxi python/pyaturan.pyx

# The extension module setup.py ACTUALLY writes. There is no python/pyaturan.so and never was:
# `build_ext --inplace` produces the interpreter-versioned name, so naming the short one as a
# target made that rule re-run on every single make, and left $(TARGET_DIR)/pyaturan.so below
# depending on a file with no rule at all — which is why `make clean && make` failed outright
# with "No rule to make target python/pyaturan.cpython-310-...so". Asking the interpreter for the
# suffix keeps this working across Python versions instead of hard-coding 310.
PY_EXT = python/pyaturan$(shell python3 -c 'import sysconfig; print(sysconfig.get_config_var("EXT_SUFFIX"))')

#copy pyaturan.so from python dir to uranus dir
COPY_FILE = pyaturan.so
TARGET_DIR = uranus

target = $(addprefix $(TARGET_DIR)/,$(COPY_FILE))

all: uran python $(target)

libaturan.a: $(PARAM_OUTPUTS) $(LIB_OBJ) $(ATURAN_OBJ) $(XML_OBJ)
	ar rcs libaturan.a $(LIB_OBJ) $(ATURAN_OBJ) $(XML_OBJ)

uran: libaturan.a $(ATURAN_CLI_OBJ)
	$(CXX) $(CFLAGS) $(ATURAN_CLI_OBJ) -L. -laturan $(LDFLAGS) -o cli/uran

# ONE recipe, ONE run. param.py writes all six outputs in a single pass, so this is a GROUPED
# target (&:, GNU make 4.3+). Written with a plain `:` it was six independent rules that happened
# to share a recipe, and make ran param.py once per output — seven concurrent invocations were
# visible in a -j8 log, all writing the same files.
$(PARAM_OUTPUTS) &: param.py
	python3 param.py

# cUranusModel.h #includes UranusParams.h.inc, cUranusModel.cpp includes the other two, and that
# header reaches every translation unit in ATURAN_OBJ and the CLI. So the generated files are a
# genuine prerequisite of those objects and saying so is what makes a regenerated parameter set
# actually take effect. This REPLACES the `rm -f planet/cUranusModel.o` that used to sit inside
# the recipe above, which was wrong twice over: it named only one of the twelve objects that
# include the header, and under -j it raced against the compile of that very object.
$(ATURAN_OBJ) $(ATURAN_CLI_OBJ): $(PARAM_OUTPUTS)

# Verify the shared headers have not diverged between the planet models. Same target as ATJUP,
# ATSAT and ATNEPT carry, with one addition they do not need: this was added while ATURAN held NO
# shared headers, and a bare `md5sum -c` on an empty list exits 1 with "no properly formatted
# checksum lines found". Reporting the empty case in its own words keeps the target honest —
# "nothing to verify" must not be indistinguishable from "verified". The branch stays now that
# the manifest is populated, because it costs nothing and the next fork will need it.
.PHONY: check-shared
check-shared:
	@lines=`grep -v '^#' planet/SHARED.md5 | grep -v '^[[:space:]]*$$' || true`; \
	if [ -z "$$lines" ]; then \
		echo "check-shared: no shared headers in ATURAN yet — nothing to verify"; \
	else \
		echo "$$lines" | md5sum -c - && echo "shared headers OK"; \
	fi

analyze:
	analyze-build make

python: libaturan.a $(PY_EXT)

$(PY_EXT): python/pyaturan.pyx python/aturan.pxd libaturan.a
	cd python && python3 setup.py build_ext --inplace

# copy the extension module from python dir to uranus dir
$(TARGET_DIR)/pyaturan.so: $(PY_EXT)
	cp $< $@


planet/%.o: planet/%.cpp
	$(CXX) $(CFLAGS) -c $< -o $@

lib/%.o: lib/%.cpp
	$(CXX) $(CFLAGS) -c $< -o $@

cli/%.o: cli/%.cpp
	$(CXX) $(CFLAGS) -c $< -o $@

tinyxml2/%.o: tinyxml2/%.cpp
	$(CXX) $(CFLAGS) -c $< -o $@

%.o: %.cpp
	$(CXX) $(CFLAGS) -c $<

.PHONY: clean
clean:
	\rm -vf $(LIB_OBJ) $(ATURAN_OBJ) $(XML_OBJ) $(ATURAN_CLI_OBJ) $(DEPS) $(PARAM_OUTPUTS) uran libaturan.a
	\rm -vf python/*.so python/*.o python/pyaturan.cpp
	\rm -rf python/build/

# Header dependencies, generated by -MMD above. The leading - keeps the first build (when no .d
# files exist yet) from failing on the missing includes.
-include $(DEPS)
