# Top-level Makefile
# Builds everything: planet, Python interface and CLI interface

CC     = /usr/lib/ggdb
CFLAGS = -Wall -fPIC -std=c++11 -Ilib -Iplanet -Itinyxml2 -fopenmp


# Common files for the shared lib (libaturan.a)
LIB_OBJ = lib/Array.o lib/Array_2D.o lib/Array_1D.o lib/Config.o lib/Utils.o lib/FFT.o

ATURAN_OBJ = planet/cUranusModel.o planet/PrintMsg_Uran.o planet/RungeKutta_Uran.o \
planet/RHS_Uran.o planet/ParaView_Uran.o planet/Thermo_Uran.o \
planet/InitVariables_Uran.o planet/InitVelocity_Uran.o planet/FileIO_Uran.o \
planet/Pressure_Uran.o planet/SaturationAdjustmentUran.o \
planet/Delegations_Uran.o

XML_OBJ = tinyxml2/tinyxml2.o

# Command line objects
ATURAN_CLI_OBJ = cli/uran.o cli/DefaultStream.o

# Because there are so many parameters, many of the files are autogenerated
PARAM_OUTPUTS = planet/cUranusDefaults.cpp.inc planet/UranusLoadConfig.cpp.inc \
planet/UranusParams.h.inc uranus/config_aturan.xml python/uranus_pxd.pxi python/pyaturan.pyx

#copy pyaturan.so from python dir to uranus dir
COPY_FILE = pyaturan.so
TARGET_DIR = uranus

target = $(addprefix $(TARGET_DIR)/,$(COPY_FILE))

all: uran python $(target)

libaturan.a: $(PARAM_OUTPUTS) $(LIB_OBJ) $(ATURAN_OBJ) $(XML_OBJ)
	ar rcs libaturan.a $(LIB_OBJ) $(ATURAN_OBJ) $(XML_OBJ)

uran: libaturan.a $(ATURAN_CLI_OBJ)
	$(CXX) $(CFLAGS) $(ATURAN_CLI_OBJ) -L. -laturan $(LDFLAGS) -o cli/uran

$(PARAM_OUTPUTS): param.py
# explicitly clean dependent files
	rm -f planet/cUranusModel.o
	python3 param.py

analyze:
	analyze-build make

python: libaturan.a python/pyaturan.so

python/pyaturan.so: python/pyaturan.pyx python/aturan.pxd libaturan.a
	cd python && python3 setup.py build_ext --inplace

# copy pyaturan.so from python dir to uranus dir
$(TARGET_DIR)/pyaturan.so: python/pyaturan.cpython-310-x86_64-linux-gnu.so
	cp $< $@


planet/%.o: planet/%.cpp
	$(CXX) $(CFLAGS) -c $< -o $@

lib/%.o: lib/%.cpp
	$(CXX) $(CFLAGS) -c $< -o $@

cli/%.o: cli/%.cpp
	$(CXX) $(CFLAGS) -c $< -o $@

tinyxml2/%.o: tinyxml2/%.cpp
	$(CXX) $(CFLAGS) -c $< -o $@

%.o: %.cpp
	$(CXX) $(CFLAGS) -c $<

.PHONY: clean
clean:
	\rm -vf $(LIB_OBJ) $(ATURAN_OBJ) $(XML_OBJ) $(ATURAN_CLI_OBJ) $(PARAM_OUTPUTS) uran libaturan.a
	\rm -vf python/*.so python/*.o python/pyaturan.cpp
	\rm -rf python/build/
